services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12059001
      POSTGRES_DB: rss_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rss_network

  redis:
    image: redis:6
    networks:
      - rss_network

  web:
    build: .
    command: ./wait-for-it.sh db:5432 -- gunicorn -w 1 -b 0.0.0.0:5000 --timeout 60 run:app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - rss_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  worker:
    build: .
    command: ./wait-for-it.sh db:5432 -- celery -A app.celery worker --loglevel=info
    depends_on:
      - db
      - redis
    networks:
      - rss_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

  beat:
    build: .
    command: ./wait-for-it.sh db:5432 -- celery -A app.celery beat --loglevel=info
    depends_on:
      - db
      - redis
    networks:
      - rss_network
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  db_data:

networks:
  rss_network:
    driver: bridge