version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12059001
      POSTGRES_DB: rss_db
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - rss_network

  redis:
    image: redis:6
    networks:
      - rss_network

  web:
    build: .
    command: gunicorn -w 1 -b 0.0.0.0:5000 --timeout 60 run:app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    networks:
      - rss_network

  worker:
    build: .
    command: celery -A worker.celery worker --loglevel=info
    depends_on:
      - redis
    networks:
      - rss_network

  beat:
    build: .
    command: celery -A worker.celery beat --loglevel=info
    depends_on:
      - redis
    networks:
      - rss_network

volumes:
  db_data:

networks:
  rss_network:
    driver: bridge